version: '3.8'
services:
  db:
    container_name: point-management
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'point'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes

    ports:
      - '3366:3306'
    expose:
      - '3306'
    volumes:
      - './volumes/mysql/default:/var/lib/mysql'
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
