

spring:
  batch:
    job:
      names: ${job.name:NONE} # spring.batch.job.names를 job.name으로 치환
    jdbc:
      initialize-schema: always # batch에서 사용하는 스키마 생성여부를 always로
  jpa:
    show-sql: true # sql 로그로 남기기를 true로 변경
    hibernate:
      ddl-auto: validate # entity를 보고 자동으로 데이터베이스 생성 여부를 validate (생성은 안하고 검증만)로 변경

  datasource:
    url: jdbc:mysql://localhost:3366/point
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  sql:
    init:
      mode: never
