spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://localhost:3366/point
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  sql:
    init:
      mode: always